[package]
name = "ulid-rs-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = { version = "0.5.0", features = ["uuid", "serde"] }
uuid = { version = "0.8", features = ["v4"] }
