version: "3"

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/llib/postgresql/data

volumes:
  postgres-data:
