[[setting]]
os = "macOS"
version = 11.5
users = ["Bob", "Alice"]
[[setting]]
os = "macOS"
version = 11.5
users = ["Bob", "Alice"]

[[setting]]
os = "macOS"
version = 11.5
users = ["Bob", "Alice"]

[[setting]]
os = "macOS"
version = 11.5
users = ["Bob", "Alice"]

[[setting]]
os = "macOS"
version = 11.5
users = ["Bob", "Alice"]

