version: '3'

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
